### PR TITLE
index post relationships

### PR DESCRIPTION
**Pull request by macbookandrew**
This adds FacetWP integration for all configured MB Relationships.

Here is a screenshot of the FacetWP settings showing all configured relationships available as data sources:

screenshot

### CODE REVIEW

**Comment by macbookandrew** [comment]
@rilwis is there a repo for this? https://metabox.io/plugins/meta-box-facetwp-integrator/

I’d be happy to submit a PR to update it as well

**Comment by rilwis** [comment]
@macbookandrew **This** is the repo for https://metabox.io/plugins/meta-box-facetwp-integrator/. Or did you meant to mention another plugin?

**Comment by macbookandrew** [comment]
Sorry, I was wondering if there’s a repo that contains the content of this page: https://metabox.io/plugins/meta-box-facetwp-integrator/

I was going to submit a PR with some changes to note the new post relationship facet indexing.

After looking at it again, looks like it’s a WP template for a product CPT, so it would have to be manually updated instead.

**Comment by rilwis** [comment]
Ah, this is a normal WP page and the content is updated manually by us. Let me update it.

**Pull request merged**
